---
version: '3'

services:
  igv-webapp:
    container_name: igv-webapp
    image: dceoy/igv-webapp:latest
    volumes:
      - ${PWD}:/wd:ro
    working_dir: /wd
    ports:
      - 8080:8080
    entrypoint:
      - npm
    command:
      - start
      - --prefix=/usr/local/src/igv-webapp
  samtools-qc:
    container_name: samtools-qc
    image: dceoy/samtools:latest
    volumes:
      - ./bin:/opt/bin
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - /opt/bin/samtools_qc.sh
    command:
      - --version
